[package]
name = "drive-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
simple_logger = "1.11"
shelve = "0.1"
threadpool = "1.8"
tempfile = "3.2"

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"
